# NumPy Operations

In [1]:
# import NumPy
import numpy as np


In [ ]:
# create random number arrays
num1 = np.random.randint(0, 200, 10)
num2 = np.random.randint(0,200, 10)

# Add operation
sum_of_nums = num1 + num2 

# Subtract operation
subtract_of_nums = num1 - num2

# Multiply operation
multiply_of_nums = num1 * num2

# Divide by operation
divide_of_nums = num1 / num2 


# use of trigonometric functions
sin_num1 = np.sin(num1)
sin_num2 = np.sin(num2)

cos_num1 = np.cos(num1)
cos_num2 = np.cos(num2)

# Sqrt
square_root_num1 = np.sqrt(num1)
square_root_num2 = np.sqrt(num2)

# log
log_num1 = np.log(num1)
log_num2 = np.log(num2)


print("*"*20,"NumPy Operations","*"*20)
print("\n")

print(f"Original num1 NumPy array: {num1}\n")
print(f"Original num2 NumPy array: {num2}\n")


print(f"Example of Add Operation\n{sum_of_nums}")

print("\n")
print(f"Example of Subtract Operation\n{subtract_of_nums}")

print("\n")
print(f"Example of Multiplication Operation\n{multiply_of_nums}")


print("\n")
print(f"Example of Division Operation\n{multiply_of_nums}")

print("\n")
print(f"Examples of Sinus Operation\n")
print(f"sin_num1: {sin_num1}\n")
print(f"sin_num2: {sin_num2}\n")

print(f"Examples of Cosinus Operation\n")
print(f"cos_num1: {cos_num1}\n")
print(f"cos_num2: {cos_num2}\n")

print(f"Examples of Square Root Operation")
print(f"square_root_num1: {square_root_num1}\n")
print(f"square_root_num2: {square_root_num2}\n")

print(f"Examples of Logaritmic Operation")
print(f"log_num1: {log_num1}\n")
print(f"log_num2: {log_num2}\n")


******************** NumPy Operations ********************


Example of Add Operation
[166  89 100  77 202   8 173 356  98 181]


Example of Subtract Operation
[ -24  -43   22   -7 -168    6  -53  -22   28  167]


Example of Multiplication Operation
[ 6745  1518  2379  1470  3145     7  6780 31563  2205  1218]
