# Numpy Exercises
1- Create a numpy array with (30, 78, 47, 98, 41, 12, 14, 69, 32) values

2- Create a numpy array between 5 and 15 

3- Create a numpy array of 10 to 75 in increment five by five

4- Create a 20-element array of zeros

5- Create a 8-element array of ones

6- Generate 10 equally spaced numbers between 40 and 120

7- Generate 10 random numbers between 23-59

8- Generate 10 random numbers between -1 and 1

9- Create matrix between 0-100 in 2*3 dimensions 

10- Find the sum of rows and columns of the produced matrix 

11- Find the sum, mean, std of the produced matrix

12- Find the index of the maximum element

13- Print the first three elements of an array containing numbers between 100 and 200

14 - Print the elements of the generated array in reverse order

15- Select the first row of produced matrix

16- Find the value of the generated matrix in first row and second column

17- Select the first element in all rows of the generated matrix

18- Print the third power of each element of the generated matrix

19- Which of the matrix elements produced is a positive even number (create a numpy array between -100 and 100)

20 - Make a copy of the generated matrix and add 15 to each element.

In [1]:
# import NumPy
import numpy as np

# 1.
np_array = np.array([30, 78, 47, 98, 41, 12, 14, 69, 32])
print(f"Result of first question: {np_array}")

Result of first question: [30 78 47 98 41 12 14 69 32]


In [2]:
# 2.
np_arange_arr = np.arange(5, 15)
print(f"Result of second question: {np_arange_arr}")

Result of second question: [ 5  6  7  8  9 10 11 12 13 14]


In [3]:
# 3. 
np_increment_arr = np.arange(10, 75, 5)
print(f"Result of third question: {np_increment_arr}") 

Result of third question: [10 15 20 25 30 35 40 45 50 55 60 65 70]


In [6]:
# 4.
zeros_arr = np.zeros(20)
print(f"Result of fourth question: {zeros_arr}\nLen of zeros_arr: {len(zeros_arr)} ")

Result of fourth question: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Len of zeros_arr: 20 


In [8]:
# 5. 
ones_arr = np.ones(8)
print(f"Result of fifht question: {ones_arr}\nLen of zeros_arr: {len(ones_arr)} ")

Result of fifht question: [1. 1. 1. 1. 1. 1. 1. 1.]
Len of zeros_arr: 8 


In [ ]:
# 6. 
linspace_np_arr = np.linspace(40, 120, 10)
print(f"Result of sixth question: {linspace_np_arr}\nLength of linspace_np_arr: {len(linspace_np_arr)}\nAmount of increment between elements: {linspace_np_arr[-1] - linspace_np_arr[-2]}")

Result of sixth question: [ 40.          48.88888889  57.77777778  66.66666667  75.55555556
  84.44444444  93.33333333 102.22222222 111.11111111 120.        ]
Length of linspace_np_arr: 10
Amount of increment between elements: 8.888888888888886


In [14]:
# 7.
random_arr = np.random.randint(23, 59, 10)
print(f"Result of seventh question: {random_arr}\nLenght of random_arr: {len(random_arr)}")

Result of seventh question: [27 44 23 28 48 28 53 47 35 26]
Lenght of random_arr: 10


In [20]:
# 8
random_nums = np.random.randn(10)
print(f"Result of eighth question: {random_nums}\nLength of random_nums: {len(random_nums)}")

Result of eighth question: [-0.25287092  0.41596062  1.05169335  1.44487621 -0.14325857  0.43442784
  1.74215623  0.04187697 -0.67557684 -0.68327673]
Length of random_nums: 10


In [22]:
# 9
multi_np_arr = np.random.randint(0, 100, (2, 3))
print(f"Result of ninth question: {multi_np_arr}\nShape of multi_np_arr: {multi_np_arr.shape}\nDimension of multi_np_arr: {multi_np_arr.ndim} ")

Result of ninth question: [[ 9 38 72]
 [86 27 68]]
Shape of multi_np_arr: (2, 3)
Dimension of multi_np_arr: 2 


In [23]:
# 10.
sum_of_rows = multi_np_arr.sum(axis = 1)
sum_of_cols = multi_np_arr.sum(axis = 0)

print(f"Result of tenth question:\nSum of each rows: {sum_of_rows}\nSum of each columns: {sum_of_cols}")

Result of tenth question:
Sum of each rows: [119 181]
Sum of each columns: [ 95  65 140]


In [27]:
# 11. 
sum_of_multi_np_arr = multi_np_arr.sum()
mean_of_multi_np_arr = multi_np_arr.mean()
std_of_multi_np_arr = multi_np_arr.std()
variance_of_multi_np_arr = multi_np_arr.var()
max_element = multi_np_arr.max()
max_element_index = multi_np_arr.argmax()
min_element = multi_np_arr.min()
min_element_index = multi_np_arr.argmin()
print(f"Result of eleventh question: \n")
print(f"Sum of multi_np_arr: {sum_of_multi_np_arr}\n")
print(f"Mean of multi_np_arr: {mean_of_multi_np_arr}\n")
print(f"Standart deviation of multi_np_arr: {std_of_multi_np_arr}\n")
print(f"Variance of multi_np_arr: {variance_of_multi_np_arr}\n")
print(f"Maximum value of multi_np_arr: {max_element}\n")
print(f"The index of the maximum value in multi_np_arr: {max_element_index}\n")
print(f"Minimum value of multi_np_arr: {min_element}\n")
print(f"The index of the minimum value in multi_np_arr: {min_element_index}\n")



Result of eleventh question: 

Sum of multi_np_arr: 300

Mean of multi_np_arr: 50.0

Standart deviation of multi_np_arr: 27.258026340878022

Variance of multi_np_arr: 743.0

Maximum value of multi_np_arr: 86

The index of the maximum value in multi_np_arr: 3

Minimum value of multi_np_arr: 9

The index of the minimum value in multi_np_arr: 0



In [28]:
# 12. 
print("Result of twelfth question:\n")
print(f"The index of the maximum value in multi_np_arr: {max_element_index}\n")

Result of twelfth question:

The index of the maximum value in multi_np_arr: 3



In [33]:
# 13
new_rand_arr = np.random.randint(100, 200, 10)
print(f"Result of thirteenth question")
print(f"Original new_rand_arr: {new_rand_arr}\nThe first three elements of new_rand_arr: {new_rand_arr[:3]}")

Result of thirteenth question
Original new_rand_arr: [198 110 128 180 147 167 105 185 146 143]
The first three elements of new_rand_arr: [198 110 128]


In [32]:
# 14.
reversed_new_rand_arr = new_rand_arr[::-1]
print("Result of fourteenth question:")
print(f"Reversed_new_randd_arr: {reversed_new_rand_arr}")

Result of fourteenth question:
Reversed_new_randd_arr: [104 117 131 100 140 145 171 158 158 176]


In [35]:
# 15.
print("Result of fifteenth question:")
print(f"Original multi_np_arr: {multi_np_arr}\n")
first_row_multi_dim_arr = multi_np_arr[1, :]
print(f"First row of multi_np_arr: {first_row_multi_dim_arr}")

Result of fifteenth question:
Original multi_np_arr: [[ 9 38 72]
 [86 27 68]]

First row of multi_np_arr: [86 27 68]


In [ ]:
# 16.
first_row_second_col = multi_np_arr[1, 2]
print("Result of sixteenth question:")
print(f"First row and second column of multi_np_arr: {first_row_second_col}")

Result of sixteenth question:
First row and second column of multi_np_arr: 68


In [37]:
# 17. 
selected_all_rows_arr = multi_np_arr[:, 0]
print(f"Result of seventeenth question:\nFirst element of all rows: {selected_all_rows_arr}") 

Result of seventeenth question:
First element of all rows: [ 9 86]


In [38]:
# 18.
third_exponent_of_arr = multi_np_arr ** 3
print(f"Result of eighteenth question:\nThe third exponent of all numbers in the multi_np_arr: {third_exponent_of_arr}")

Result of eighteenth question:
The third exponent of all numbers in the multi_np_arr: [[   729  54872 373248]
 [636056  19683 314432]]


In [ ]:
# 19. 
print("Result of nineteenth question:\n")
new_np_arr = np.random.randint(-100, 100, 20)
print("new_np_arr: ",new_np_arr)
filtered = new_np_arr[(new_np_arr > 0) & (new_np_arr % 2 == 0)]
even_elements = filtered
print(f"Positive even numbers in new_np_arr:{filtered}")

Result of nineteenth question:

new_np_arr:  [ 78  91 -52 -47  22  42  59 -55  83 -88  13 -24  82  56  -5 -97  71 -73
 -22 -24]
Positive even numbers in new_np_arr:[78 22 42 82 56]


In [48]:
new_np_copy = new_np_arr.copy()
added_new_np_copy = new_np_copy + 15
print(f"Result of twentieth question:")
print(f"Original new_np_copy: {new_np_copy}\n")
print(f"Fifteen added numpy array: {added_new_np_copy}")

Result of twentieth question:
Original new_np_copy: [ 78  91 -52 -47  22  42  59 -55  83 -88  13 -24  82  56  -5 -97  71 -73
 -22 -24]

Fifteen added numpy array: [ 93 106 -37 -32  37  57  74 -40  98 -73  28  -9  97  71  10 -82  86 -58
  -7  -9]
