# NumPy Operations

In [1]:
# import NumPy
import numpy as np


In [7]:
# create random number arrays
num1 = np.random.randint(0, 200, 10)
num2 = np.random.randint(0,200, 10)

# Add operation
sum_of_nums = num1 + num2 

# Subtract operation
subtract_of_nums = num1 - num2

# Multiply operation
multiply_of_nums = num1 * num2

# Divide by operation
divide_of_nums = num1 / num2 


# use of trigonometric functions
sin_num1 = np.sin(num1)
sin_num2 = np.sin(num2)

cos_num1 = np.cos(num1)
cos_num2 = np.cos(num2)

# Sqrt
square_root_num1 = np.sqrt(num1)
square_root_num2 = np.sqrt(num2)

# log
log_num1 = np.log(num1)
log_num2 = np.log(num2)


print("*"*20,"NumPy Operations","*"*20)
print("\n")

print(f"Original num1 NumPy array: {num1}\n")
print(f"Original num2 NumPy array: {num2}\n")


print(f"Example of Add Operation\n{sum_of_nums}")

print("\n")
print(f"Example of Subtract Operation\n{subtract_of_nums}")

print("\n")
print(f"Example of Multiplication Operation\n{multiply_of_nums}")


print("\n")
print(f"Example of Division Operation\n{multiply_of_nums}")

print("\n")
print(f"Examples of Sinus Operation\n")
print(f"sin_num1: {sin_num1}\n")
print(f"sin_num2: {sin_num2}\n")

print(f"Examples of Cosinus Operation\n")
print(f"cos_num1: {cos_num1}\n")
print(f"cos_num2: {cos_num2}\n")

print(f"Examples of Square Root Operation")
print(f"square_root_num1: {square_root_num1}\n")
print(f"square_root_num2: {square_root_num2}\n")

print(f"Examples of Logaritmic Operation")
print(f"log_num1: {log_num1}\n")
print(f"log_num2: {log_num2}\n")
print("*" *57)


******************** NumPy Operations ********************


Original num1 NumPy array: [ 36  17 162 161  27   5 134 144  68 114]

Original num2 NumPy array: [117  83 188 129  10 131  94 174 166 129]

Example of Add Operation
[153 100 350 290  37 136 228 318 234 243]


Example of Subtract Operation
[ -81  -66  -26   32   17 -126   40  -30  -98  -15]


Example of Multiplication Operation
[ 4212  1411 30456 20769   270   655 12596 25056 11288 14706]


Example of Division Operation
[ 4212  1411 30456 20769   270   655 12596 25056 11288 14706]


Examples of Sinus Operation

sin_num1: [-0.99177885 -0.96139749 -0.97845035 -0.70240779  0.95637593 -0.95892427
  0.88592482 -0.49102159 -0.89792768  0.78498039]

sin_num2: [-0.68969794  0.96836446 -0.47552367 -0.19347339 -0.54402111 -0.81160339
 -0.24525199 -0.93646197  0.48329156 -0.19347339]

Examples of Cosinus Operation

cos_num1: [-0.12796369 -0.27516334  0.20648223 -0.71177476 -0.29213881  0.28366219
 -0.46382887  0.8711474   0.44014302  0.6

In [ ]:
multi_dim_num1 = num1.reshape(2, 5)
multi_dim_num2 = num2.reshape(2, 5)

print("-"*10,"Operations of Multi Dimensional Array","-"*10, "\n")
print("Reshaped num1 array:", multi_dim_num1,"\n")
print(f"Reshaped num2 array: {multi_dim_num2}\n")

# Vertical stack method
v_stacked_arr = np.vstack((multi_dim_num1, multi_dim_num2))
print(f"Vertical Stacked Arr:\n{v_stacked_arr}\n ")  

h_stacked_arr = np.hstack((multi_dim_num1, multi_dim_num2))
print(f"Horizontal Stacked Arr:\n{h_stacked_arr}\n")

# print(len("---------- Operations of Multi Dimensional Array ----------")) 59


---------- Operations of Multi Dimensional Array ---------- 

Reshaped num1 array: [[ 36  17 162 161  27]
 [  5 134 144  68 114]] 

Reshaped num2 array: [[117  83 188 129  10]
 [131  94 174 166 129]]

Vertical Stacked Arr:
[[ 36  17 162 161  27]
 [  5 134 144  68 114]
 [117  83 188 129  10]
 [131  94 174 166 129]]
 
Horizontal Stacked Arr:
[[ 36  17 162 161  27 117  83 188 129  10]
 [  5 134 144  68 114 131  94 174 166 129]]

59
