# Work With Numpy Arrays

In [2]:
# import numpy 
import numpy as np


In [ ]:
# create a numpy array
# add a title 
print("*"*27,"Basic Numpy Array Operations","*"*27)


np_array = np.array([1, 9, 2, 8, 3, 7, 4, 6, 5])
print(f"np_array: {np_array}")
print("*"*85)

# arange array
arange_array = np.arange(17, 45, 4) # start, stop, step
print(f"arange_array: {arange_array}\nItems in arange_array: {arange_array.size}")
print("*"*85)

# zeros method for 1D arrays
zeros_array= np.zeros((3, 2)) # shape (rows, columns)
print(f"zeros_array:\n{zeros_array}\nItems in zeros_array: {zeros_array.size}")
print("*"*85)

# ones method for 2D arrays
ones_array = np.ones((3, 2)) # shape (rows, columns)
print(f"ones_array:\n{ones_array}\nItems in ones_array: {ones_array.size}")
print("*"*85)

# linspace method for 1D arrays
linspace_array = np.linspace(0, 100, 10) # start, stop, number of items
print(f"linspace_array: {linspace_array}\nItems in linspace_array: {linspace_array.size}")    
print("*"*85)


# randint method for 1D and 2D arrays
random_array = np.random.randint(0, 10) # random integer between 0 and 10
print(f"random_array:{random_array}")
print("*"*85)



random_array_2d = np.random.randint(0, 20, (3, 3)) # random integers between 0 and 20 in a 3x3 array
print(f"random_array_2d:\n{random_array_2d}\nItems in random_array_2d: {random_array_2d.size}")
print("*"*85)

# random.rand method 
random_rand_array = np.random.rand(5) # random floats between 0 and 1
print(f"random_rand_array: {random_rand_array}")
print("*"*85)




*************************** Basic Numpy Array Operations ***************************
np_array: [1 9 2 8 3 7 4 6 5]
*************************************************************************************
arange_array: [17 21 25 29 33 37 41]
Items in arange_array: 7
*************************************************************************************
zeros_array:
[[0. 0.]
 [0. 0.]
 [0. 0.]]
Items in zeros_array: 6
*************************************************************************************
ones_array:
[[1. 1.]
 [1. 1.]
 [1. 1.]]
Items in ones_array: 6
*************************************************************************************
linspace_array: [  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]
Items in linspace_array: 10
*************************************************************************************
random_array:1
*************************************************************************

In [ ]:
# np_array manipulations
print("*"*28,"Numpy Array Manipulations","*"*28)
np_array = np.arange(0,50)
print(f"np_array: {np_array}")
print("*"*83)

# reshape the array to 5 rows and 10 columns
np_array_reshaped = np_array.reshape(5, 10)  
print(f"np_array_reshaped:\n{np_array_reshaped}\nItems in np_array_reshaped: {np_array_reshaped.size}")
print("*"*83)

# print rows and columns total sum
rows_total_sum = np_array_reshaped.sum(axis=1)  # sum along rows
print(f"rows_total_sum: {rows_total_sum}")
print("*"*83)


columns_total_sum = np_array_reshaped.sum(axis=0)  # sum along columns
print(f"columns_total_sum: {columns_total_sum}")
print("*"*83) 

**************************** Numpy Array Manipulations ****************************
np_array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
***********************************************************************************
np_array_reshaped:
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
Items in np_array_reshaped: 50
***********************************************************************************
rows_total_sum: [ 45 145 245 345 445]
***********************************************************************************
columns_total_sum: [100 105 110 115 120 125 130 135 140 145]
***********************************************************************************


In [21]:
# add a title for the next section
print("*"*28,"Numpy Array Statistics","*"*28)

# generate random integers between 20 and 80
rnd_nums = np.random.randint(20, 80, 8)  # random integers between 20 and 80
print(f"rnd_nums: {rnd_nums}")
print("*"*80)

# print maximum and minimum values, their indices, mean, standard deviation, variance, and median
print(f"Maximum value in rnd_nums: {rnd_nums.max()}")
print("*"*80)
print("Index of maximum value in rnd_nums:", rnd_nums.argmax())
print("*"*80)

print(f"Minimum value in rnd_nums: {rnd_nums.min()}")
print("*"*80)
print(f"Index of minimum value in rnd_nums:", rnd_nums.argmin())
print("*"*80)

print(f"Mean value in rnd_nums: {rnd_nums.mean()}")
print("*"*80)

print(f"Standart deviation in rnd_nums: {rnd_nums.std()}")
print("*"*80)

print(f"Variance in rnd_nums: {rnd_nums.var()}")
print("*"*80)

print(f"Median value in rnd_nums: {np.median(rnd_nums)}")
print("*"*80)

# print(len("**************************** Numpy Array Statistics ****************************"))

**************************** Numpy Array Statistics ****************************
rnd_nums: [77 22 58 79 78 30 65 58]
********************************************************************************
Maximum value in rnd_nums: 79
********************************************************************************
Index of maximum value in rnd_nums: 3
********************************************************************************
Minimum value in rnd_nums: 22
********************************************************************************
Index of minimum value in rnd_nums: 1
********************************************************************************
Mean value in rnd_nums: 58.375
********************************************************************************
Standart deviation in rnd_nums: 20.40182283522725
********************************************************************************
Variance in rnd_nums: 416.234375
******************************************************************